#
# This file is part of Saft.
#
# (c) Konrad Abicht <hi@inspirito.de>
# (c) Natanael Arndt <arndt@informatik.uni-leipzig.de>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
#

language: php

php:
    - '5.6'
    - '7.0'
    - '7.1'
    - '7.2'
    - nightly

matrix:
    fast_finish: true
    include:
        - php: hhvm
    allow_failures:
        - php: hhvm

cache:
    directories:
        - $HOME/.composer/cache

sudo: true

before_install:
    - composer require satooshi/php-coveralls:*
    - travis_retry composer install --dev --no-interaction

script: vendor/bin/phpunit --coverage-clover gen/coverage/clover.xml


after_script: php vendor/bin/coveralls -v
